#include <windows.h>
#include <iostream>
#include "porthack.h"
using namespace std;

void PortHack() {
    cout << "porsche firebird	prince	rosebud\n";
    Sleep(200);
    cout << "password	guitar	butter	beach	jaguar\n";
    Sleep(200);
    cout << "12345678	chelsea	united	starcraft	great\n";
    Sleep(200);
    cout << "1234	black	turtle	7777777	cool\n";
    Sleep(200);
    cout << "pussycat	diamond	steelers	muffin	cooper\n";
    Sleep(200);
    cout << "12345	nascar	tiffany	redsox	1313\n";
    Sleep(200);
    cout << "dragon	jackson	zxcvbn	star	scorpio\n";
    Sleep(200);
    cout << "qwerty	cameron	tomcat	testing	mountain\n";
    Sleep(200);
    cout << "696969	654321	golf	shannon	madison\n";
    Sleep(200);
    cout << "mustang	computer	bond007	murphy	987654\n";
    Sleep(200);
    cout << "letmein	amanda	bear	frank	brazil\n";
    Sleep(200);
    cout << "baseball	wizard	tiger	hannah	lauren\n";
    Sleep(200);
    cout << "master	Iwasphone	doctor	dave	japan\n";
    Sleep(200);
    cout << "michael	money	gateway	eagle1	knickers\n";
    Sleep(200);
    cout << "football	phoenix	gators	11111	squirtle\n";
    Sleep(200);
    cout << "shadow	mickey	angel	mother	stars\n";
    Sleep(200);
    cout << "monkey	bailey	junior	nathan	apple\n";
    Sleep(200);
    cout << "abc123	knight	thx1138	raiders	alexis\n";
    Sleep(200);
    cout << "pass	iceman	porno	steve	aaaa\n";
    Sleep(200);
    cout << "bucket	tigers	badboy	forever	bonnie\n";
    Sleep(200);
    cout << "6969	purple	debbie	angela	peaches\n";
    Sleep(200);
    cout << "jordan	andrea	spider	viper	jasmine\n";
    Sleep(200);
    cout << "harley	alicorn	melissa	ou812	kevin\n";
    Sleep(200);
    cout << "ranger	dakota	booger	jake	matt\n";
    Sleep(200);
    cout << "iwantu	aaaaaa	1212	lovers	qwertyui\n";
    Sleep(200);
    cout << "jennifer	player	flyers	suckit	danielle\n";
    Sleep(200);
    cout << "hunter	sunshine	fish	gregory	baman\n";
    Sleep(200);
    cout << "ponies	morgan	ilovecorm	buddy	4321\n";
    Sleep(200);
    cout << "2000	starwars	matrix	whatever	4128\n";
    Sleep(200);
    cout << "test	boomer	piderman	young	runner\n";
    Sleep(200);
    cout << "batman	cowboys	scooby	nicholas	swimming\n";
    Sleep(200);
    cout << "trustno1	edward	jason	lucky	dolphin\n";
    Sleep(200);
    cout << "thomas	charles	walter	helpme	gordon\n";
    Sleep(200);
    cout << "tigger	girls	bimp	jackie	casper\n";
    Sleep(200);
    cout << "robert	booboo	boston	monica	stupid\n";
    Sleep(200);
    cout << "access	coffee	braves	midnight	iloveboats\n";
    Sleep(200);
    cout << "love	xxxxxx	yankee	college	saturn\n";
    Sleep(200);
    cout << "buster	bulldog	lover	boby	gemini\n";
    Sleep(200);
    cout << "1234567	ncc1701	barney	bort	apples\n";
    Sleep(200);
    cout << "soccer	rabbit	victor	brian	august\n";
    Sleep(200);
    cout << "hockey	peanut	tucker	mark	3333\n";
    Sleep(200);
    cout << "killer	john	princess	startrek	canada\n";
    Sleep(200);
    cout << "george	johnny	mercedes	sierra	blazer\n";
    Sleep(200);
    cout << "sexy	gandalf	5150	leather	earlgamer\n";
    Sleep(200);
    cout << "andrew	boop	doggie	232323	hunting\n";
    Sleep(200);
    cout << "charlie	winter	zzzzzz	4444	kitty\n";
    Sleep(200);
    cout << "superman	brandy	gunner	beavis	rainbow\n";
    Sleep(200);
    cout << "\n";
    cout << "\n";
    cout << "\n";
    cout << "Password found!" << endl;
    Sleep(3000);
}